### ISSUE TITLE
HU-B-08: Resultados de Entrenamiento Bakcend

### ISSUE THREAD

**Issue by shiomar-salazar** [shiomar-salazar/MISW-PF-Grupo1-Backend#100]
Implementar HU segun Wiki: https://github.com/shiomar-salazar/MISW4501-2024-Grupo1/wiki/HU%E2%80%90B%E2%80%9008

**Comment by jm-carrillo** [comment]
![Image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/111403006/edca53b0-0a81-4326-ac22-0d78eb39f2b7)
