### ISSUE TITLE
Correccion Modelo de Concurrencia

### ISSUE THREAD

**Issue by shiomar-salazar** [shiomar-salazar/MISW-PF-Grupo1-Backend#51]
Completar trabajo del entregable con comentarios del TutorCompletar trabajo del entregable con comentarios del TutorCompletar trabajo del entregable con comentarios del TutorCompletar trabajo del entregable con comentarios del TutorCompletar trabajo del entregable con comentarios del Tutor

**Comment by stonejfg** [comment]
se corrige modelo de concurrencia
