### ISSUE TITLE
Registro de Servicio Web

### ISSUE THREAD

**Issue by shiomar-salazar** [shiomar-salazar/MISW-PF-Grupo1-Backend#72]
Implementacion de HU segun Wiki creada:
https://github.com/shiomar-salazar/MISW4501-2024-Grupo1/wiki/HU-W-03

**Comment by haibergalindouniandes** [comment]
Se implementa el formulario para el registro de servicios.

Cambios integrados con el PR: 
[Pull Request 2](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Web/pull/2)

Formulario:
![image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/110913673/bf129c2c-818f-4320-b9ae-f27eaf5b5c2f)

Validación de datos del formulario:
![image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/110913673/0e16f890-1a61-4bb9-af06-06a7b239320b)

Confirmación de servicio registrado:
![image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/110913673/64b45ce6-cd1d-42d4-ac5a-44ee0a11ac5b)

Registro en base de datos:
![image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/110913673/97d44ac6-8db4-48c4-bb2c-c9bf04e1f46a)
