### ISSUE TITLE
Registro de Servicio Backend

### ISSUE THREAD

**Issue by shiomar-salazar** [shiomar-salazar/MISW-PF-Grupo1-Backend#75]
Implementacion de HU segun Wiki creada:
https://github.com/shiomar-salazar/MISW4501-2024-Grupo1/wiki/HU-B-03

**Comment by haibergalindouniandes** [comment]
Se realiza la implementación de funcionalidad de registro de servicios.
La información de consumo, asi como las posibles respuestas de la funcionalidad se encuentran actualizadas en la wiki:

https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/wiki/HU-B-03#ejemplo-de-request-y-response-del-servicio

![image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/110913673/f3e7d800-3364-4a29-b5cd-f193b0025d3e)
