### ISSUE TITLE
Crear Plan de Entrenamiento Backend

### ISSUE THREAD

**Issue by shiomar-salazar** [shiomar-salazar/MISW-PF-Grupo1-Backend#76]
Implementacion de HU segun Wiki creada:
https://github.com/shiomar-salazar/MISW4501-2024-Grupo1/wiki/HU-B-04

**Comment by haibergalindouniandes** [comment]
Se implementa la funcionalidad de creación de plan de entrenamiento. La información de consumo, asi como las posibles respuestas de la funcionalidad se encuentran relacionadas en la wiki:
https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/wiki/HU-B-04#ejemplo-de-request-y-response-del-servicio 

![image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/110913673/6803dee2-4a76-4df0-91b1-80c428c2a945)
