### ISSUE TITLE
HU-B-11: Resultados de Alimentacion Backend

### ISSUE THREAD

**Issue by shiomar-salazar** [shiomar-salazar/MISW-PF-Grupo1-Backend#77]
Implementar HU segun wiki: https://github.com/shiomar-salazar/MISW4501-2024-Grupo1/wiki/HU%E2%80%90B%E2%80%9011

**Comment by haibergalindouniandes** [comment]
Se realiza la implementación del API Registro Resultados de Alimentación Backend

![image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/110913673/926cf99b-6215-470a-809d-7ed496e97c51)

Se realizan pruebas de cobertura

![image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/110913673/96e4c481-f98d-4362-957a-22c33740366e)
