### ISSUE TITLE
HU-W-04: Crear plan de entrenamiento - Web

### ISSUE THREAD

**Issue by shiomar-salazar** [shiomar-salazar/MISW-PF-Grupo1-Backend#81]
Implementar HU segun wiki: https://github.com/shiomar-salazar/MISW4501-2024-Grupo1/wiki/HU-W-04

**Comment by jm-carrillo** [comment]
![Image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/111403006/5c6d8405-47e6-4e1e-b032-adeb79907468)
