### ISSUE TITLE
HU-W-11: Resultados de Alimentacion Web

### ISSUE THREAD

**Issue by shiomar-salazar** [shiomar-salazar/MISW-PF-Grupo1-Backend#82]
Implementar HU segun Wiki: https://github.com/shiomar-salazar/MISW4501-2024-Grupo1/wiki/HU%E2%80%90W%E2%80%9011

**Comment by haibergalindouniandes** [comment]
Se realiza la implementación de la HU-W-11: Resultados de Alimentacion Web se adjuntan evidencias:

Pull Request merged:
https://github.com/shiomar-salazar/MISW-PF-Grupo1-Web/pull/6

Cobertura:
![image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/110913673/ea8708d3-c5e4-4d6d-8d8d-fd7c16a37e38)

Pruebas unitarias:
![image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/110913673/dbd480ca-3cff-46fb-a8c5-8096eb3b033d)

Pruebas  E2E
![image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/110913673/85658a9b-d16b-40af-84be-5848b5e9ccdb)

Flujo CI/CD:
![image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/110913673/b40f9118-0534-4939-8e36-a06e928353ab)

Pantalla resultados de Alimentacion Web:
![image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/110913673/5362b3d0-896f-4601-ae4c-82c3fccf82b8)
