### ISSUE TITLE
HU-B-05: Servicio de Consultas Backend

### ISSUE THREAD

**Issue by shiomar-salazar** [shiomar-salazar/MISW-PF-Grupo1-Backend#84]
Implementar HU segun wiki: https://github.com/shiomar-salazar/MISW4501-2024-Grupo1/wiki/HU-B-05

**Comment by jm-carrillo** [comment]
endpoints:
/resultado-entrenamiento/usuario/<id_usuario>
/plan-alimentacion/usuario/<id_usuario>

![Image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/111403006/7ec5c1ff-9b5b-4253-b375-e8becb336d0c)
