### ISSUE TITLE
HU-B-07: Generar Alerta/Notificacion Backend

### ISSUE THREAD

**Issue by shiomar-salazar** [shiomar-salazar/MISW-PF-Grupo1-Backend#86]
Implementar HU segun Wiki: https://github.com/shiomar-salazar/MISW4501-2024-Grupo1/wiki/HU%E2%80%90B%E2%80%9007

**Comment by haibergalindouniandes** [comment]
Se implementan las funcionalidades para enviar alarma de emergencia y notificación masivo de eventos.

Enviar Alerta Emergencia:
![image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/110913673/c3488e03-dd8d-4af0-bb4f-03f7eec6bf99)

Notificar evento masivo:: 
![image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/110913673/0761cbb9-9e05-477c-b6f6-11e70de553ac)

Registrar usuario - Cliente - Contactos emergencia:
![image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/110913673/2a54c6c5-e7d8-414c-9fad-bc3515000741)
