### ISSUE TITLE
Pipeline de CI/CD Web

### ISSUE THREAD

**Issue by shiomar-salazar** [shiomar-salazar/MISW-PF-Grupo1-Backend#87]
Implementar HU segun wiki: https://github.com/shiomar-salazar/MISW4501-2024-Grupo1/wiki/HU%E2%80%90D%E2%80%9002

**Comment by haibergalindouniandes** [comment]
Se realiza la implementación del Pipeline de CI/CD para el proyecto de Web.

Se adjunta evidencia del flujo exitoso.

![image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/110913673/86dcecfa-287b-497b-9cdb-db8e2d2295b9)

![image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/110913673/23b03e9c-91ea-4718-ac02-8d1eabdca03f)
