### ISSUE TITLE
HU-W-08: Ver Eventos Registrados Web

### ISSUE THREAD

**Issue by shiomar-salazar** [shiomar-salazar/MISW-PF-Grupo1-Backend#94]
Implementar HU segun wiki: https://github.com/shiomar-salazar/MISW4501-2024-Grupo1/wiki/HU-W-08

**Comment by haibergalindouniandes** [comment]
Se realiza la implementación de la HU.

![image](https://github.com/shiomar-salazar/MISW-PF-Grupo1-Backend/assets/110913673/9138d0ea-f329-474b-b25b-95165fdee5a0)

Se intregan cambios con la rama main, PR https://github.com/shiomar-salazar/MISW-PF-Grupo1-Web/pull/12.
